---
title: "Assessing the knowledge of AIDS amongst Women in 1997 Vietnam"
author: 
  - Jacob Yoke Hong Si
thanks: "Code and data are available at: https://github.com/jacobyokehongsi/Assessing_the_Knowledge_of_AIDS_amongst_Women_in_1997_Vietnam"
date: "`r format(Sys.time(), '%d %B %Y')`"
abstract: "How does the knowledge of AIDS amongst Vietnamese women differ? Utilizing the data from the 1997 Vietnam Demographic and Health Survey (DHS), we look to depict the demographics of AIDS knowledge of Vietnamese women whilst varying characteristics such as their age, marital status, residence region and education. third sentence: specify the headline result; and a fourth sentence about implications. We found that most families are small, well-off and in good mental health, and that immigrants make up about one fifth of the population, with a propensity to settle in larger cities and urban centers. We also discuss possible factors that may have influenced this family image, including Canada's investment in family planning and immigration levels planning. \\par \\textbf{Keywords:} AIDS, vietnamese women, source, age group, regions, levels of education"
output:
  bookdown::pdf_document2
toc: FALSE
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

# Introduction

The Demographic and Health Surveys (DHS) is a nationwide household survey that provides data for a myriad of evaluation indicators with respect to health, nutrition and population. A few examples of topics include education, HIV/AIDS knowledge and tobacco use. In addition to the topics mentioned, each survey also collects comprehensive socio-demographic data including the respondents' age, marital status, residential area, etc. 

The DHS program was established in 1984 and has provided technical assistance to over 300 demographic and health surveys in more than 90 countries with its main objective to enhance and develop data collection and utilization by host countries for monitoring and evaluating demographic indicators in order to devise high quality policy development decisions.

In these regards, the DHS program has been majorly successful with the data collected often serving as crucial assistance to the government's policy making to help improve the well-being of the population. Furthermore, the program data is also accessible to health care providers, researchers and post-secondary institutions that have informed research with respect to the public health of the citizens. The program has thus been an invaluable source for quantitative and statistical methods to further understand the demographics of the population holistically. For these aforementioned reasons, the DHS program serves an important and fundamental role within a country's statistical system. (https://en.wikipedia.org/wiki/Demographic_and_Health_Surveys)

The Demographic and Health Survey on the knowledge of AIDS in Vietnam assesses the knowledge and attitudes of Vietnamese women regarding the prevention of infection with the AIDS virus. The AIDS virus, also known as Acquired immunodeficiency syndrome, is a chronic, potentially life endangering condition caused by the HIV (human immunodeficiency virus) which is a sexually transmitted infection. The HIV would damage the body's immune system to fight off infections and diseases. Since there is no present cure for HIV, prevention is crucial to ensure that the population does not contract AIDS/HIV. (https://www.mayoclinic.org/diseases-conditions/hiv-aids/symptoms-causes/syc-20373524)

The DHS on AIDS knowledge aims to provide the National Committee for AIDS Prevention, which is the organization responsible for the dissemination of AIDS information in Vietnam, information that includes modes of AIDS transmission and potential prevention strategies. With the available data, it would assist the organization in designing social policies that will best inform the Vietnamese population of AIDS prevention. Thus, the DHS is one of the key aspects of the foundation in informing Vietnamese women about the preventive measures that could be taken against AIDS.

In this paper, we will explore the percentage of ever-married women by knowledge of AIDS and its source, according to their background characteristics during 1997 Vietnam. Specifically, I will address the following research questions:

- At what age group are Vietnamese women least informed about AIDS?
- Are there specific regions in Vietnam where the knowledge is lacking and why this is the case?
- What is the most prevalent source of AIDS knowledge in Vietnam?
- Does education affect the knowledge of AIDS and if so, do different levels of education affect the knowledge differently?

# Data

# Model

# Results

# Discussion

## First discussion point

If my paper were 10 pages, then should be be at least 2.5 pages. The discussion is a chance to show off what you know and what you learnt from all this. 

## Second discussion point

## Third discussion point

## Weaknesses and next steps


\newpage

\appendix

# Appendix {-}

\newpage


# References


